### ISSUE TITLE
Etale Kohomologie 2.34.1

### ISSUE THREAD

**Issue by mbid** [yishn/Uni#10]
Ich denke, da sollte

> [...] mit einem Object _C_ und **End**(_C_)=_G_ [...]

stehen, denn sonst ist die Existenz von Endomorphismen, die keine Isomorphismen sind, nicht ausgeschlossen.

**Comment by yishn** [comment]
Es gibt keine Endomorphismen, die keine Isomorphismen sind, da G eine Gruppe ist und alles ist invertierbar. Oder liege ich da falsch?
