### ISSUE TITLE
Etale Kohomologie 2.12 falsche Begründung

### ISSUE THREAD

**Issue by mbid** [yishn/Uni#9]
Die dargestellten Garben haben nicht die Form Hom_stg(-, U), sondern Hom_{Top(X)}(-, U), deshalb ist 1.14 nicht anwendbar.

**Comment by yishn** [comment]
In der Kategorie `Top(X) = X_top` sind die 'Homomorphismen' gerade die stetigen Abbildungen, oder etwa nicht?

**Comment by yishn** [comment]
Ja, ich werde die Begründung einfach entfernen, weil die Aussage klar ist.
